# Builds developing environment for rumors-api
#
version: '2'
services:
  db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    ports:
      - "62222:9200"
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"
    environment:
      - "path.repo=/usr/share/elasticsearch/data"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Prevent elasticsearch eating up too much memory

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.0
    depends_on:
      - db
    environment:
      ELASTICSEARCH_URL: http://db:9200 # Through docker network, not exposed port
    ports:
      - "6222:5601"

  api:
    image: kkarczmarczyk/node-yarn:6.9@sha256:c6a5e8623886262fe8a3aed488ecf8aa2c0b43c99ec438c9c4d66d3ea7849494
    container_name: rumors-api
    depends_on:
      - db
    working_dir: "/srv/www"
    entrypoint: npm run dev
    volumes:
      - ".:/srv/www"
    environment:
      NODE_CONFIG: '{"ELASTICSEARCH_URL": "http://db:9200"}'
    ports:
      - "5000:5000"
